---

- import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Add user to Docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
  become: true

# Required for some Ansible modules
- name: Install docker-py
  pip:
    name: docker-py
  become: true
